Fix Build Failed on CI
Fixed failed build due to an ESLint error in ./src/components/ReleaseNotesButton.tsx:

Error: '_' is assigned a value but never used. @typescript-eslint/no-unused-vars (line 70)